config/routes.rb
Wallpanels::Application.routes.draw do
  get '/designs'         => 'pages#all_designs'
  get '/projects'        => 'pages#projects'
  get '/designs/*design' => 'pages#design'
  get '/contacts'        => 'pages#contacts'
  get '/eco_products'    => 'pages#eco_products'
  root :to => 'pages#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
require 'will_paginate/array'

class PagesController < ApplicationController
  def index
    @slideshow_images = Dir.glob("app/assets/images/slideshow/*.jpg")
  end

  def all_designs
    @thumbnails = Dir.glob("app/assets/images/products/*-1_tn.jpg")
  end

  def design
    @design = params[:design]
    @thumbnails = Dir.glob("app/assets/images/products/#{@design}*_tn.jpg")
  end

  def eco_products
  end

  def contacts
  end

  def projects
    @thumbnails = Dir.glob("app/assets/images/projects/*_tn.jpg").paginate(page: params[:page], per_page: 20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Wall Accent</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="content-wrapper">
      <nav id="main-navigation">
        <ol>
          <li><%= link_to t('About Us'), root_path %></li>
          <li><%= link_to t('Our Designs'), designs_path %></li>
          <li><%= link_to t('Eco Products'), eco_products_path %></li>
          <li><%= link_to t('Projects'), projects_path %></li>
          <li><%= link_to t('Contact Us'), contacts_path %></li>
        </ol>
      </nav>
    </div>
  </header>
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->

  <div class="content-wrapper clearfix">
    <%= yield %>
  </div>

  <footer>
    <div class="content-wrapper">
      <p>2013 Wall Accent &copy; <%=t 'All rights reserved' %></p>
    </div>
  </footer>

<script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40726712-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

  </body>
</html>

app/views/pages/all_designs.html.haml
.main-image
  %h1
    =t :text_1
  %p
    =t :text_2

  = link_to image_tag "products/bricks-1.jpg"

%ul.thumbnails.clearfix
  - @thumbnails.each do |thumbnail|
    %li
      = link_to "/designs/#{File.basename(thumbnail).split('-').first}" do
        = image_tag "products/#{File.basename(thumbnail)}"
      %span
        =t File.basename(thumbnail).split('-').first.capitalize

:javascript
  $(document).ready(function() {
    $('.thumbnails li img').mouseover(function() {
      var src = $(this).attr('src').replace("_tn", "");
      $('.main-image img').attr('src', src);
    });
  });

app/views/pages/contacts.bg.html.haml
%h1 Wall Accent

%p Румен Стоянов
%p бул. Скобелев 115
%p Русе, 7000
%p Мобилен: 0897 845 850
%p и-мейл: info@wall-accent.com

app/views/pages/contacts.en.html.haml
%h1 Wall Accent

%p Rumen Stoyanov
%p ...
%p Rousse, 7000 Bulgaria
%p Mobile phone: +359 (0) 897 845 850
%p email: info@wall-accent.com

app/views/pages/design.html.haml
.design-details
  %h1
    =t @design.capitalize

  %p
    =t :text_8
  %p
    =t :text_7

  %ul.clearfix
    - @thumbnails.each do |thumbnail|
      %li
        = image_tag "products/#{File.basename(thumbnail)}"

.design-image
  = image_tag "products/#{@design}-1.jpg"

:javascript
  $(document).ready(function() {
    $('.design-details ul li img').mouseover(function() {
      var src = $(this).attr('src').replace("_tn", "");
      $('.design-image img').attr('src', src);
    });
  });

app/views/pages/eco_products.bg.html.haml
.eco-product-text
  %h1 Екологично Чист Продукт

  %p
    Суровият материал, който се използва за производство на панелите за
    стена е влакнестият остатък от стъблата на захарната тръстика. Ето
    защо цялостният продукт е 100% рециклируем.

  %p
    Остатъка от захарната тръстика е един от най-подновируемите източници
    в света, защото захарната тръстика може да се добива 3 пъти в годината.
    Общият световен добив е повече от 1.2 милиарда кубични тона за година.
    3 тона от захарната тръстика е еквивалентен на 1 тон суров материал.

  %p
    Суровият материал за изработката на панелите за стена е също така
    компостируем и 100% биоразградим. Посредством рециклиране, вместо
    унищожение на продукта, ние създаваме истински екологично чисти
    продукти!

  .images
    = image_tag 'ecoproduct_1.jpg'
    = image_tag 'ecoproduct_2.jpg'

.eco-product-image
  = image_tag 'ecoproduct_3.jpg'

app/views/pages/eco_products.en.html.haml
%h1 Green and Eco-friendly product

%p
  The raw material used for the production of the WallArt 3d wall panels is the
  fibrous residue remaining after sugarcane stalks are crushed to extract their
  juice. Therefore we can claim that this fibrous residue used as the raw
  material is 100% recycled.

%p
  Bagasse, as a residue of sugarcane, is one of the world's most renewable
  sources because sugarcane can be harvested up to 3 times a year. The total
  harvest worldwide is more than 1.2 billion metric tons yearly. 3 ton of
  sugarcane equals 1 ton of bagasse.

%p
  The raw material of the WallArt 3d wall panels, bagasse, is also compostable
  and therefore 100% biodegradable at the end of its life cycle. By re-using the
  waste of sugarcane production instead of burning it we can say it is a real
  eco-friendly product!

= image_tag 'ecoproduct_1.jpg'

app/views/pages/index.html.haml
.index-page
  .slider-wrapper
    #slider.nivoSlider
      - @slideshow_images.each do |image|
        = image_tag "slideshow/#{File.basename(image)}"

  %h1
    =t :text_3
  %p
    =t :text_4
  %p
    =t :text_5
  %p
    =t :text_6

:javascript
  $(document).ready(function() {
    $('#slider').nivoSlider({
      effect: 'fold',
      controlNav: false,
      directionNav: false,
      pauseTime: 5000,
      randomStart: true
    });
  });

app/views/pages/projects.bg.html.haml
.main-image
  %h1 Завършени Проекти

  = image_tag "projects/project-1.jpg"

.thumbnails
  %ul.clearfix
    - @thumbnails.each do |thumbnail|
      %li
        = image_tag "projects/#{File.basename(thumbnail)}"

  = will_paginate(@thumbnails, :outer_window => 0, :inner_window => 0, :previous_label => '&laquo;', :next_label => '&raquo;')

:javascript
  $(document).ready(function() {
    $('.thumbnails li img').mouseover(function() {
      var src = $(this).attr('src').replace("_tn", "");
      $('.main-image img').attr('src', src);
    });
  });